# Generated by Django 5.2.1 on 2025-05-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_app_delete_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='animation',
            field=models.BooleanField(default=False, verbose_name='Animation'),
        ),
        migrations.AddField(
            model_name='app',
            name='screen',
            field=models.BooleanField(default=False, verbose_name='Screen'),
        ),
    ]
