# Generated by Django 5.2.1 on 2025-05-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_app_animation_app_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='animation',
            field=models.BooleanField(default=False, verbose_name='Анимации'),
        ),
        migrations.AlterField(
            model_name='app',
            name='screen',
            field=models.BooleanField(default=False, verbose_name='Экраны'),
        ),
    ]
