# Generated by Django 5.2.1 on 2025-05-31 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_app_animation_alter_app_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.CreateModel(
            name='AppImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apps/photos/', verbose_name='Фото')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.app')),
            ],
        ),
        migrations.CreateModel(
            name='AppVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='apps/videos/', verbose_name='Видео')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='web.app')),
            ],
        ),
    ]
